### ISSUE TITLE
`_Check` was not declared in this scope.

### ISSUE THREAD

**Issue by o11c** [PySide/pyside2#3]
Fails to build for me, on Debian amd64. `_Check` is not defined:

    pyside_build/py3.4-qt5.4.2-64bit-release/pyside/PySide/QtGui/PySide/QtGui/qinputevent_wrapper.cpp:231:    if (_Check(pyArg) && (pythonToCpp = Shiboken::Conversions::isPythonToCppConvertible(Shiboken::Conversions::PrimitiveTypeConverter<ulong>(), (pyArg)))) {
    pyside_build/py3.4-qt5.4.2-64bit-release/pyside/PySide/QtGui/PySide/QtGui/qinputevent_wrapper.cpp:322:    if (!_Check(pyIn) && (pythonToCpp = Shiboken::Conversions::isPythonToCppConvertible(Shiboken::Conversions::PrimitiveTypeConverter<ulong>(), (pyIn)))) {

**Comment by IronManMark20** [comment]
Can you tell us the steps you took to build? Did you point to qmake?

**Comment by ctismer** [comment]
Yes, this looks like a strangely failed code generation, maybe some old shiboken.

On my build, these lines look like
```
    // Overloaded function decisor
    // 0: setTimestamp(ulong)
    if ((pythonToCpp = Shiboken::Conversions::isPythonToCppConvertible(Shiboken::Conversions::PrimitiveTypeConverter<ulong>(), (pyArg)))) {
        overloadId = 0; // setTimestamp(ulong)
    }

```

I think we should redirect people to _not_ use these repositories alone, but always use the pyside-setup2 bundle and the setup.py script.

**Comment by IronManMark20** [comment]
I agree. We could add READMEs that point to pyside-setup2 for all the submodules, then alter that README with build instructions. I can do that for you if you want.

**Comment by ctismer** [comment]
@IronManMark20 Oh, if you like to do that, great, very welcome!! :-)

**Comment by IronManMark20** [comment]
Sure, I'll make some PRs soon.

**Comment by o11c** [comment]
I did it all through pyside-setup2, pointing to my local copy of qt5-qmake (qmake in PATH is for qt4). I *do* have all the dependencies also installed on my system, but I would expect the setup.py to prefer the bundled copies.

From the looks of surrounding code, this is a string substitution of the form `%s_Check`, it should be a fatal error to substitute nothing.

**Comment by IronManMark20** [comment]
Could you git pull? Perhaps a submodule is outdated?

**Comment by o11c** [comment]
Hm, just noticed that pyside-setup2 was replaced by pyside2-setup, will retry after pulling.

**Comment by o11c** [comment]
Nope, still happens.

The exact command I run: `python3 setup.py --qmake=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake --jobs=4 build`

**Comment by ctismer** [comment]
Ahhh... that is the tip of the Qt5 repos?
I just managed to build for Qt5.5.0. Can this be the problem?
Then we probably should keep a list of minimum and maximum supported version...

**Comment by IronManMark20** [comment]
@ctismer I might be able to grab the version from the qmake flag. then we can warn people there version of qt is not supported.

**Comment by o11c** [comment]
My system Qt is 5.4, that's supposed to be supported.

Everything else is likely from your repos.

**Comment by ctismer** [comment]
This is weird. But I only tested on Debian stable, this is Qt5.3 . I cannot find such a _Check thing in the shiboken sources.

**Comment by ctismer** [comment]
@o11c ok, it must be coming from shibokengenerator.cpp, maybe line 1048:
```
        return QString("%1_Check").arg(pythonPrimitiveTypeName((const PrimitiveTypeEntry*)type));
```
But I'm sorry that I cannot help you more with this. The opposite should happen, because this is
a new project in alpha state, and we need to fix bugs and urgently missing things that are changed
in Qt5.
So if you can find out what is wrong, then your contribution will be welcome.

**Comment by o11c** [comment]
`ShibokenGenerator::initPrimitiveTypesCorrespondences()` is missing a case for `unsigned long int`. I'm not sure whether it treats that differently than `unsigned long` though, and I am *certain* that it does not use the `ulong` there.

I have no idea why this actually works for anyone else.

**Comment by o11c** [comment]
Closing as I have isolated the issue and made a PR, even though it's not perfect.
