### ISSUE TITLE
Bad behaviour when a Python exception happens in a slot used in Javascript

### ISSUE THREAD

**Issue by empyrical** [PySide/pyside2#40]
Here's a code example that demonstrates what I mean:

```py
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtQml import *

class TestObject(QObject):
    @Slot(result=str)
    def testMethod(self):
        raise Exception("Just testing.")

app = QGuiApplication(())

engine = QQmlEngine()
testObject = TestObject()

engine.evaluate("""
(function (testObject) {
    try {
        // No error is raised on the JS side of things.
        // It'll dump an error to stdout and return an empty string (or the empty
        // equivalent of whatever type you return)
        console.log('Output:', testObject.testMethod());
    } catch (e) {
        console.error('Got an error!');
        console.error(e);
    }
})
""").call([engine.newQObject(testObject)])
```

You'll see this if you run this script:

```py
$ python3 qmljs_test.py
Traceback (most recent call last):
  File "qmljs_test.py", line 8, in testMethod
    raise Exception("Just testing.")
Exception: Just testing.
qml: Output:
```

This might be a bit tricky to pull off - there's two things one would have to figure out to pull this off:

 * The APIs for raising JS exceptions are all private and undocumented so care should be had when using them.
 * The slot calling code will have to be made to figure out if it's being called from a JavaScript engine and also somehow get a reference to the JavaScript engine

Also, presumably there's similar issues when exceptions happen when QtWebChannel calls a slot. But one thing at a time ;)

**Comment by empyrical** [comment]
This was actually surprisingly trivial to get sorta-working! Just need to figure out some details and a PR should be ready maybe in a day or two when I have more time to tinker.

However, important question: How bad of an idea would it be to add a dependency on Qt's private headers? I know that means we'd have to worry about the API changing between releases, but there's no other solution I can think of to stop this bug from happening other than dipping into private APIs. PyQt currently segfaults if a Python exception happens in QML, and I don't think going that route would be ideal. Also, the QtQml module does already use `QQmlPrivate` for the register type function, but somehow it doesn't need private headers to use that. Looking for input from someone more experienced on this sorta thing

**Comment by ctismer** [comment]
I am not that experienced, but it is of course some times necessary to open private
APIs. I think this is ok to do, if we build things in a way that checks the API for
future changes. Maybe we can think of a way to secure that, with tests and assertions
and whatever. I would like to prevent the mess that I had with the port from happening again.

**Comment by empyrical** [comment]
Yeah, thankfully since I only needed to use a handful of private APIs for this it hopefully won't be too hard to maintain but it would be a good idea if I went back and documented where I found these APIs
