### ISSUE TITLE
Build fails on Debian Sid with Qt 5.5.1 QtGui::QGuiApplication

### ISSUE THREAD

**Issue by f3nix** [PySide/pyside2#51]
Hi,
I'm having trouble building on Debian Sid. G++ 5.3.1. Python 2.7.11. 64 bit.
With VS2013 everything compiles just fine (Win7 64 bit, Python 2.7.11).

With QtGui
During generation I get:
```
	signature 'QGuiApplication(int&,char**,int)' for function modification in 'QGuiApplication' not found. Possible candidates: QGuiApplication(PySequence) in QGuiApplication, QGuiApplication(QGuiApplication) in QGuiApplication, QGuiApplication(int&,char**) in QGuiApplication
	There's no user provided way (conversion rule, argument removal, custom code, etc) to handle the primitive argument type 'char **' in function 'QGuiApplication::QGuiApplication(int & argc, char ** argv)'.
```

During compilation I get:
```
canning dependencies of target QtGui
[ 48%] Building CXX object PySide2/QtGui/CMakeFiles/QtGui.dir/PySide2/QtGui/qguiapplication_wrapper.cpp.o
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp: In function ‘void QGuiApplicationConstructor(PyObject*, PyObject*, QGuiApplicationWrapper*)’:
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:100:15: error: no match for ‘operator=’ (operand types are ‘QGuiApplicationWrapper’ and ‘QGuiApplicationWrapper*’)
         *cptr = new QGuiApplicationWrapper(QGuiApplicationArgCount, QGuiApplicationArgValues);
               ^
In file included from /home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:41:0:
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note: candidate: QGuiApplicationWrapper& QGuiApplicationWrapper::operator=(const QGuiApplicationWrapper&)
 class QGuiApplicationWrapper : public QGuiApplication
       ^
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note:   no known conversion for argument 1 from ‘QGuiApplicationWrapper*’ to ‘const QGuiApplicationWrapper&’
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp: In function ‘int Sbk_QGuiApplication_Init(PyObject*, PyObject*, PyObject*)’:
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:449:80: error: no matching function for call to ‘QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char*&)’
                     cptr = new (addr) ::QGuiApplicationWrapper(cppArg0, cppArg1);
                                                                                ^
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:113:1: note: candidate: QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char**)
 QGuiApplicationWrapper::QGuiApplicationWrapper(int & argc, char ** argv) : QGuiApplication(argc, argv) {
 ^
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:113:1: note:   no known conversion for argument 2 from ‘char*’ to ‘char**’
In file included from /home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:41:0:
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note: candidate: QGuiApplicationWrapper::QGuiApplicationWrapper(const QGuiApplicationWrapper&)
 class QGuiApplicationWrapper : public QGuiApplication
       ^
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note:   candidate expects 1 argument, 2 provided
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:452:73: error: no matching function for call to ‘QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char*&)’
                     cptr = new ::QGuiApplicationWrapper(cppArg0, cppArg1);
                                                                         ^
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:113:1: note: candidate: QGuiApplicationWrapper::QGuiApplicationWrapper(int&, char**)
 QGuiApplicationWrapper::QGuiApplicationWrapper(int & argc, char ** argv) : QGuiApplication(argc, argv) {
 ^
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:113:1: note:   no known conversion for argument 2 from ‘char*’ to ‘char**’
In file included from /home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.cpp:41:0:
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note: candidate: QGuiApplicationWrapper::QGuiApplicationWrapper(const QGuiApplicationWrapper&)
 class QGuiApplicationWrapper : public QGuiApplication
       ^
/home/f3nix/devel/freecad/pyside-qt5/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/pyside2/PySide2/QtGui/PySide2/QtGui/qguiapplication_wrapper.h:35:7: note:   candidate expects 1 argument, 2 provided
PySide2/QtGui/CMakeFiles/QtGui.dir/build.make:1144: polecenia dla obiektu 'PySide2/QtGui/CMakeFiles/QtGui.dir/PySide2/QtGui/qguiapplication_wrapper.cpp.o' nie powiodły się
make[2]: *** [PySide2/QtGui/CMakeFiles/QtGui.dir/PySide2/QtGui/qguiapplication_wrapper.cpp.o] Błąd 1
CMakeFiles/Makefile2:440: polecenia dla obiektu 'PySide2/QtGui/CMakeFiles/QtGui.dir/all' nie powiodły się
make[1]: *** [PySide2/QtGui/CMakeFiles/QtGui.dir/all] Błąd 2
Makefile:127: polecenia dla obiektu 'all' nie powiodły się
make: *** [all] Błąd 2
```

Happy New Year! :smile:

Cheers,
Mateusz

EDIT: Add some more info. Fix copy/paste.

**Comment by f3nix** [comment]
Hi,
below are some diffs between linux and windows generated wrappers. Maybe they can be of some use.
Windows generated files compile just fine under Linux.

[qguiapplication_wrapper.diff.zip](https://github.com/PySide/pyside2/files/76421/qguiapplication_wrapper.diff.zip)

[qguiapplication_wrapper_header.diff.zip](https://github.com/PySide/pyside2/files/76420/qguiapplication_wrapper_header.diff.zip)

Cheers,
Mateusz

**Comment by thopiekar** [comment]
@f3nix How did you setup shiboken?
```cmake -DBUILD_TESTS=OFF .```?
Could you please try to build Shiboken with BUILD_TESTS=ON (default)?

Thanks!

**Comment by f3nix** [comment]
Hi,

I'm using pyside2-setup
after
```
python setup.py build
```
I get the build error from OP.

```
$ pwd
/home/f3nix/devel/pyside2-setup/pyside_build/py2.7-qt5.5.1-64bit-release/shiboken2

$ cat CMakeCache.txt | grep BUILD_TESTS
BUILD_TESTS:BOOL=False
```

So it does not set it as default... (but it obviously should).

How to change that?

Thanks.

Cheers,
Mateusz

PS. Is there a way to force the build script not to compile everything from scratch after every change?

**Comment by gbaty** [comment]
Hello!
On my system (debian with Qt 5.5.1 manually built), QGuiApplication constructor differs depending on preprocessing variable "Q_QDOC":
If Q_QDOC is defined, constructor has two arguments **(int &argc, char **argv);** else 3 **QGuiApplication(int &argc, char **argv, int = ApplicationFlags)**

See:
[qguiapplication.h:l75](http://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/kernel/qguiapplication.h#n75)
```cpp
class Q_GUI_EXPORT QGuiApplication : public QCoreApplication
{
    Q_OBJECT
    [...]
public:
#ifdef Q_QDOC
    QGuiApplication(int &argc, char **argv);
#else
    QGuiApplication(int &argc, char **argv, int = ApplicationFlags)
```

In pyside global.h.in, Q_QDOC is defined at [L363](https://github.com/PySide/pyside2/blob/master/PySide2/global.h.in#L363), and if "ENABLE_MAC" or "ENABLE_WIN", Q_QDOC is **undefined** at line [L380](https://github.com/PySide/pyside2/blob/master/PySide2/global.h.in#L380) but it is not the case on linux. 

I think this bug is due to an incompatibility between Qt build on linux (with Q_QDOC undefined) and PySide build on linux (with Q_QDOC defined).

If line L363 is commented (Q_QDOC never defined), this bug disappears. 

Does anybody know why we need to define Q_QDOC here and why on MAC and WIN and not on windows we disable it ?

**Comment by gbaty** [comment]
@f3nix you can build tests with `python setup.py build --build-tests`

**Comment by thopiekar** [comment]
@gbaty Good question. Maybe it is an old workaround which is not platform but Qt version specific?!

**Comment by thopiekar** [comment]
@gbaty @f3nix I think this is more useful: https://github.com/PySide/pyside2/blame/master/PySide2/global.h.in#L380

L380 is 6 years old and was surely made for Qt4. I guess many things changed here.

**Comment by f3nix** [comment]
Hi @gbaty!

Thanks for taking the time and looking into it. Great work tracking that down! :-)
Will let you know if it worked soon (added || @ENABLE_X11@).

Cheers,
Mateusz

**Comment by ctismer** [comment]
No, this was removed by me, but re-introduced later by @jumarock when he changed so much for the good.
But I never understood why this Q_DOC mess was used at all.

**Comment by f3nix** [comment]
Hi @ctismer!

You are right. Removing it causes the build to fail very early.

Cheers,
Mateusz

**Comment by ctismer** [comment]
It has a lot of effects for the data structures. There are extra fields in the structs, which are replaced by something when Q_DOC is set, and so on. A lot of the current shiboken warnings are the result of this change, which was not cleaned up, again.

**Comment by thopiekar** [comment]
To understand this kind workarounds we really need someone of the Qt core
developers. It seems to me that we are just guessing and playing with
macros and defines, which we don't understand.

When adding Q_QDOC creates a built and fairly working build for Linux I
would like to add it there (and add a compiler warning about the
workaround) to get at least working builds. I would take some time and make
working builds in my PPA and hope my recent changes in pyside2-setup makes
it installable on other distributions.

The reason why I would tolerate this mess is to create attention on our
project and to find more people who have more detailed knowledge about the
Qt core.

Even if we have some of these people already here, I think, it won't hurt
to have more of them.

**Comment by gbaty** [comment]
Thank you for your answers.
I am not a Qt core developper, but browsing source code, I can say ...
In Qt, Q_QDOC seems to be defined only in [doc/global/qt-cpp-defines.qdocconf#n3](http://code.qt.io/cgit/qt/qtbase.git/tree/doc/global/qt-cpp-defines.qdocconf#n3). This file is a configuration file for  [QDoc](http://doc.qt.io/qt-5/01-qdoc-manual.html), the tool used to generate the documentation. Current page about [QGuiApplication](http://doc.qt.io/qt-5/qguiapplication.html#QGuiApplication) confirm the first API (2 args) is used in documentation.

I wonder if it is just to make the doc nicer or prevent a QDoc failure on such arguments. 
Commit [aba8de1](http://code.qt.io/cgit/qt/qtbase.git/commit/src/gui/kernel/qguiapplication.h?id=aba8de1bee8bbb9bc6b92e761a3dda0d829a211e) corresponding to lines "#ifdef Q_QDOC ..." in qguiapplication just say "Doc: Missing documentation added and doc errors fixed."

It doesn't answer the question but might bring new clues ;)

**Comment by fxtech** [comment]
Hi! Just coming into this because I've hit the same thing. I have a custom-built Qt 5.5.1 commercial build and attempting to use pyside2-setup, with these same errors. Should I rebuild my Qt with a different set of configure flags to make the problem go away? I usually just configure with -opengl desktop. Thanks!

**Comment by f3nix** [comment]
Hi,
here is my version of a fix: https://github.com/f3nix/pyside2/tree/small-fixes-5
Commit: 33d240159ebd65d380d0af51687dc9438cce4331

Tested on:
Debian GCC 4.9.2, Qt 5.3.2, Python 2.7.9 64-bit 
Ubuntu GCC 5.2.1, Qt 5.4.2, Python 2.7.10 64-bit
Debian GCC 5.3.1, Qt 5.5.1, Python 2.7.11 64-bit

It fixes #52 too.

I can finally see:
[100%] Built target testbinding in the console :)

Would be glad if anybody could test this before I create a PR.

Thanks.
Cheers,
Mateusz

**Comment by fxtech** [comment]
Thanks f3nix! I'm ready to try it now, but I'm a bit of a github noob. I've cloned pyside2-setup and I'm working in there. Can you tell me how to get it to use your branch?

**Comment by thopiekar** [comment]
@f3nix I already added very similar lines here in order to get PPA builds working. So before creating a PR, please rebase.

**Comment by f3nix** [comment]
Fixed.
