### ISSUE TITLE
Can't "import shiboken2"

### ISSUE THREAD

**Issue by zhihaoadsk** [PySide/pyside2#61]
Build PySide2 against Qt5.5 (x64),  Python2.7(x64) and VS2012.
It doesn't work if I "import shiboken2".  It complained that 
_ImportError: dynamic module does not define init function (initeshiboken2) . _
workaround: 
1. rename shiboken2.pyd to shiboken.pyd.  
2. "import shiboken" as before (Qt4 and PySide).

**Comment by thopiekar** [comment]
That's strange.
I even didn't know shiboken was ever a module.

On Ubuntu the only library of Shiboken goes to:
```
/usr/lib/x86_64-linux-gnu/libshiboken.cpython-35m-x86_64-linux-gnu.so.1.2.2
```

As far as I know, modules should generally go to:
"/usr/lib/python3/dist-packages/"

A mistake by the packagers?

**Comment by thopiekar** [comment]
Found a problem which confirms that shiboken2 should be a Python module.
This should be the next fixed here.

**Comment by zhihaoadsk** [comment]
Awesome! Thanks Thomas!

**Comment by zhihaoadsk** [comment]
It's been fixed. Thanks Thomas! Closed the issue.
