### ISSUE TITLE
Wrong names for installed PySide wrappers

### ISSUE THREAD

**Issue by gbaty** [PySide/pyside2#68]
When installed to prefix (make install), wrappers are renamed to `${module_name}${PYTHON_MODULE_SUFFIX}${PYTHON_DEBUG_SUFFIX}`,
for example QtCore wrapper becomes `QtCore.cpython-35m-.so`.
These modules cannot be imported from python.

**Comment by thopiekar** [comment]
And I see directly the reason. Look into setup.py it should detect the multi-arch name, but it doesn't appear to be detected for some reason :/

**Comment by gbaty** [comment]
Thanks to your [commit 9822056](https://github.com/PySide/pyside2/commit/9822056181b7082b2309c6dc14ce19c90a07ea6e) I understand better why such names are kept even once installed.
Can you give some links explaining in details this part "Since Python3 all Extensions need at least  something like {extension}.cpython-35m.so".

I am going to explore to understand why arch is not detected on my system.

**Comment by thopiekar** [comment]
Thats why I love good documented commits :smile: 

Well, I just saw that in the PySide(1) packages on Ubuntu.
E.g. https://packages.debian.org/sid/amd64/python3-pyside.qtcore/filelist
But as you can see here both (Python3.4 and 3.5) have the "MULTIARCH_SUFFIX", while on Ubuntu Wily only 3.5 has it appended. I haven't tested whether Python3.4 can find a module with the long name, too.
So honestly I believed it depends on the Python version, but it doesn't seem so.

**Comment by thopiekar** [comment]
Hmm, I checked it again and it seems that a lot of modules have this mixed.
```apt-file find python | grep dist-packages | grep x86_64-linux-gnu```
Will make a commit soon, which checks for the MULTIARCH_SUFFIX to be != Null and then appends it as available. Which distribution do you use @gbaty ?

**Comment by gbaty** [comment]
Ok, I have right now a branch that do exactly that. I push it.

I use debian but in a conda environment. python3.4 provided with debian returns x86_64-linux-gnu for MULTIARCH_SUFFIX but python3.5 provided with conda returns "".

I think the answer is on how python packages are built on debian

**Comment by gbaty** [comment]
A first draft for shiboken is available in pr [shiboken2/#32](https://github.com/PySide/shiboken2/pull/32). 
Is it what you have in mind ?
For the PySide part, i suggest to keep current behavior if MULTIARCH_SUFFIX is available else
just install extensions without suffix, for example for QtCore, it will be installed as PySide2/QtCore.so

**Comment by thopiekar** [comment]
I like the patch, but you can also remove the ''' if PYTHON_MINOR_VERSION
LESS 5''' part. As you can see in the contents of the package above Python
3.4 also has the MULTIARCH_SUFFIX added. So let's remove the version check
for Python 3 at all.

**Comment by gbaty** [comment]
Changes done.
I will do equivalent patch for PySide2 soon.

Note:
It seems that multiarch support is very specific to debian and ubuntu systems. To generate python package, a patch is applied to support debian multiarch approach. We can find this patch in [debian package "python3.5_3.5.1-5.debian.tar.xz"](http://http.debian.net/debian/pool/main/p/python3.5/python3.5_3.5.1-5.debian.tar.xz). 

See file [multiarch.diff](https://github.com/PySide/pyside2/files/123311/multiarch.txt) and especially these lines:
```patch
Index: b/Python/sysmodule.c
===================================================================
--- a/Python/sysmodule.c
+++ b/Python/sysmodule.c
@@ -1696,6 +1696,15 @@ make_impl_info(PyObject *version_info)
     if (res < 0)
         goto error;
 
+    /* For Debian multiarch support. */
+    value = PyUnicode_FromString(MULTIARCH);
+    if (value == NULL)
+        goto error;
+    res = PyDict_SetItemString(impl_info, "_multiarch", value);
+    Py_DECREF(value);
+    if (res < 0)
+        goto error;
+
```
and 

```patch
Index: b/Makefile.pre.in
===================================================================
--- a/Makefile.pre.in
+++ b/Makefile.pre.in
@@ -772,6 +772,7 @@ Modules/signalmodule.o: $(srcdir)/Module
 
 Python/dynload_shlib.o: $(srcdir)/Python/dynload_shlib.c Makefile
 	$(CC) -c $(PY_CORE_CFLAGS) \
+		$(if $(MULTIARCH),-DMULTIARCH='"$(MULTIARCH)"') \
 		-DSOABI='"$(SOABI)"' \
 		-o $@ $(srcdir)/Python/dynload_shlib.c
 
@@ -783,6 +784,7 @@ Python/dynload_hpux.o: $(srcdir)/Python/
 Python/sysmodule.o: $(srcdir)/Python/sysmodule.c Makefile
 	$(CC) -c $(PY_CORE_CFLAGS) \
 		-DABIFLAGS='"$(ABIFLAGS)"' \
+		-DMULTIARCH='"$(MULTIARCH)"' \
 		-o $@ $(srcdir)/Python/sysmodule.c
```

We need to check that this is not defined in official python sources to be sure.

**Comment by thopiekar** [comment]
Ok, didn't noticed that. Please check the comment in your PR.
As this part is still work in progress it is possible that lines differ. Feel free to sync the lines between Shiboken2 and PySide2.
By the way: Many thanks for investing time.

**Comment by gbaty** [comment]
While fixing it in PySide, I have seen this code:
```cmake
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(PYTHON_EXTENSION_SUFFIX "-python${PYTHON_VERSION_MAJOR}.${PYTHON_VERSION_MINOR}-dbg")
    set(PYTHON_MODULE_SUFFIX    ".${PYTHON_MULTIARCH_SUFFIX}_d")
else()
```
The first variable is used for shiboken and pyside library names, for example: `libshiboken-python2.7-dbg-x86_64-linux-gnu.so`. The second is used for generated python modules. For example, with same build options `QtCore.x86_64-linux-gnu_d.so`.

Is there a reason why we use two different conventions ?
The second is defined by python imports convention, but is there convention for the first ? We could always use the python convention, as done for py3.

Depending on answers to this question, patch to fix this issue will differ.
Branch [gbaty/fix_issue_68](https://github.com/gbaty/pyside2/tree/fix_issue_68) fix this issue, keeping current convention but it could simply code a lot if we use same convention everywhere.

**Comment by thopiekar** [comment]
No reason actually. Again, I just took a look at the Debian packages for
PySide(1) and decided to implement it here. Do you think it would be save
to call the libraries like we want?! Shouldn't be we ask one of the
packager better, before changing these things?

**Comment by gbaty** [comment]
No, I have no idea about consequences on other platforms or packaging systems. That is why I prefer to ask.

**Comment by thopiekar** [comment]
That's why I want to keep it like that. But if you like you can play with that and share your experiences. But at the moment just apply our changes from Shiboken2 here on PySide2 for the moment.
