### ISSUE TITLE
error: Error configuring shiboken2

### ISSUE THREAD

**Issue by Kasramvd** [PySide/pyside2#71]
After running the following command:

    sudo python setup.py install --qmake=/usr/bin/qmake --cmake=/usr/bin/cmake --openssl=/usr/bin/openssl

I get this error:

```
.
.
.
CMake Error at CMakeLists.txt:4 (cmake_minimum_required):
  CMake 3.0 or higher is required.  You are running version 2.8.12.2


-- Configuring incomplete, errors occurred!
See also "/home/bluebird/pyside2/pyside2-setup/pyside_build/py2.7-qt5.2.1-64bit-release/shiboken2/CMakeFiles/CMakeOutput.log".
error: Error configuring shiboken2
```

I read another issues and they weren't helpful. I also install CMake 3.X and after getting the `version` it shows `3.3`:

```
cmake version 3.3.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
 ```

But still I get the aforementioned error. Can you help me to figure out what's the underlying reason?

**Comment by ctismer** [comment]
Hi,

I just updated the build instructions in pyside2-setup.

Besides --ignore-git, make sure that the right cmake is really used.

Also, this is an alpha version which should only be used if
you already have experience. Not to be used for anything real, and for
sure not
with sudo ;-)

FYI: I just ran successfully

time python3 setup.py build --debug --no-examples --ignore-git
--qmake=/usr/local/Cellar/qt5/5.5.1/bin/qmake --jobs=9

cheers - Chris


On 18.02.16 14:53, kasra wrote:
>
> After running the following command:
>
> |sudo python setup.py install --qmake=/usr/bin/qmake
> --cmake=/usr/bin/cmake --openssl=/usr/bin/openssl |
>
> I get this error:
>
> |. . . CMake Error at CMakeLists.txt:4 (cmake_minimum_required): CMake
> 3.0 or higher is required. You are running version 2.8.12.2 --
> Configuring incomplete, errors occurred! See also
> "/home/bluebird/pyside2/pyside2-setup/pyside_build/py2.7-qt5.2.1-64bit-release/shiboken2/CMakeFiles/CMakeOutput.log".
> error: Error configuring shiboken2 |
>
> I read another issues and they weren't helpful. I also install CMake
> 3.X and after getting the |version| it shows |3.3|:
>
> |cmake version 3.3.2 CMake suite maintained and supported by Kitware
> (kitware.com/cmake). |
>
> But still I get the aforementioned error. Can you help me to figure
> out what's the underlying reason?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PySide/pyside2/issues/71>.
>


-- 
Christian Tismer             :^)   tismer@stackless.com
Software Consulting          :     http://www.stackless.com/
Karl-Liebknecht-Str. 121     :     https://github.com/PySide
14482 Potsdam                :     GPG key -> 0xFB7BEE0E
phone +49 173 24 18 776  fax +49 (30) 700143-0023

**Comment by Kasramvd** [comment]
OK thanks.
