### ISSUE TITLE
Where can I track the status of PySide 2?

### ISSUE THREAD

**Issue by ldanzinger** [PySide/pyside2#78]
We are interested in PySide, but need support for Qt 5, so we have discovered PySide 2. This looks very promising, but we are wondering what the current status of the project is, and where we can track the progress. Is there an estimation of when PySide 2 will be roughly functionally equivalent to PySide?

**Comment by thopiekar** [comment]
Currently it depends on the contribution and testing from different people.
There is no ETA or any other plan at the moment. Just depends on how stable PySide2 is.

**Comment by ldanzinger** [comment]
Thanks @thopiekar. Are most modules in Qt 5 wrapped at this point? Or if I wanted to contribute, how do I know what needs to be worked on still?

**Comment by thopiekar** [comment]
As far as I know, yes. But there are still some missing functions, like QOpenGL* in QtGui.
You can also find warnings returned by shiboken2 about things that need to be implemented.

Well, the best is to check the issue tracker here. Other people or we are collecting todo's here, too.
