### ISSUE TITLE
pysideuic has references to import PySide in __init__.py instead of PySide2

### ISSUE THREAD

**Issue by wayne-arnold-adsk** [PySide/pyside2#80]
pysideuic  is partially updated to know about  PySide2 naming of module, but __init__.py is still using old PySide

Qt 5.6 has removed  QtDeclarative    probably shouldn't be using it here
Qt 5.6 has dropped QtWebKit by default, but can still be built manually

**Comment by thopiekar** [comment]
Same as #81
