### ISSUE TITLE
pysideuic doesn't know of Qt5 split of QtGui into QtGui and QtWidgets

### ISSUE THREAD

**Issue by wayne-arnold-adsk** [PySide/pyside2#81]
the generated code is usually  QtGui.  module name when it should be using QtWidgets
[test.zip](https://github.com/PySide/pyside2/files/186777/test.zip)

**Comment by thopiekar** [comment]
Please take a look at https://github.com/PySide/pyside2-tools/pull/3
If you can confirm that this pull request works, just give a short feedback.

Thanks!
