### ISSUE TITLE
PySide.QtGui' has no attribute 'QWidget'

### ISSUE THREAD

**Issue by qqluckiest** [pyside/pyside2#95]
Hello guys,

can someone help me about the Issue PySide.QtGui' has no attribute 'QWidget'?

I've just build and installed PySide2 with Python 3.5 and Qt5.5.1 (with Qt5.8 always build failed), when i try to run the example i got this error. How can i fix it?

Thx!

**Comment by kirbyfan64** [comment]
QWidget and other widgets are now in the `PySide.QWidget` module, not `QtGui`.

**Comment by ethanhs** [comment]
Unless things have changed in the past month, Im pretty sure everything is namespaced just like Qt5. So it is Pyside2.QtWidgets.QWidget.
